#Numpy


In [ ]:
pip install numpy

In [21]:
import numpy as py
arr1 = py.array([[1,2,3,4,5],
                 [3,4,5,6,6]])
#2row 5 column
print(arr1.shape)



(2, 5)


In [5]:
arr1 = py.array([1,2,4,5,6])
arr2 = py.array([2,4,5,6,7])
total = arr1*arr2
total

array([ 2,  8, 20, 30, 42])

In [25]:
py.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [3]:
py.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr3 = py.array([[1,2,3,2],
                 [2,4,1,1]])
arr4 = py.array([[2,4,1,1],
                 [1,2,3,2]])
total1 = py.dot(arr3,arr4.T)
print(total1)

[[15 18]
 [22 15]]


In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import pandas as pd
# we are using pandas for data manipulation
# we do have 2 import thing 1. series 2. dataframe
# Series- Set of list of values ( only row), we can donvert to dataframe


data = [1,2,3,4,5]
series = pd.Series(data)
series





0    1
1    2
2    3
3    4
4    5
dtype: int64

In [27]:
#data frame must contain row and column
dictionary = {"one":1,"two": 2,"three":3}
tup = pd.Series(dictionary)
tup

one      1
two      2
three    3
dtype: int64

In [ ]:
# Need to install for read excel file
pip install openpyxl

In [ ]:
#Data Frame
from io import StringIO
data = { "name":["vidhya","suresh","jeya","lakhmi"],"age":[20,30,40,45]}
pd.DataFrame(data)   








,name,age
0,vidhya,20
1,suresh,30
2,jeya,40
3,lakhmi,45


In [ ]:
data_excel = pd.read_excel(r"C:\Users\Vidhya\Python_Program\data.xlsx")
data_excel


,Name,Age,Department,Salary,Join_Date
0,Rajesh,29.0,Ops,60000.0,2023-05-21
1,Nasir,31.0,IT Tech,NaN,2020-11-12
2,Mathiew,NaN,Support,58000.0,2025-01-15
3,Gilbert,29.0,Ops,60000.0,2021-05-21
4,Kevin,28.0,Support,61000.0,2024-07-30
5,Navin,35.0,Support,72000.0,2023-08-19
6,NaN,40.0,IT,64000.0,2022-09-10
7,Nasir,31.0,IT Tech,NaN,2020-11-12


In [ ]:
import pandas as pd

data = {
    "name": ["vidhya", "suresh", "jeya", "lakhmi"],
    "age": [20, 30, 40, 45]
}

df = pd.DataFrame(data)

# Save - for production
df.to_pickle("data.pkl")

# Load
dfpickel = pd.read_pickle("data.pkl")
print(dfpickel)

     name  age
0  vidhya   20
1  suresh   30
2    jeya   40
3  lakhmi   45


In [ ]:
# For read HTML install this 
# python -m pip install lxml html5lib beautifulsoup4

In [18]:
import pandas as pd

html_file = pd.read_html(r"C:\Users\Vidhya\Python_Program\1.html")
print(html_file)

[     Name  Age
0  Vidhya   30]


## Data Manipulation with pandas



In [29]:
csv_file = pd.read_csv(r"C:\Users\Vidhya\Python_Program\people-100.csv")
csv_file

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Region
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer,Asia
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist,Asia
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath,India
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher,US
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon,UK
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer,India
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister,India
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer,India
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist,India


In [36]:
csv_file.isnull().sum()


Index            0
User Id          0
First Name       0
Last Name        0
Sex              0
Email            0
Phone            0
Date of birth    0
Job Title        0
Region           0
dtype: int64

In [19]:
csv_file = pd.read_csv(r"C:\Users\Vidhya\Python_Program\people-100.csv")
csv_file

#  To print the first 5 column
csv_file.head()

# To print the last 5 column
csv_file.tail()

# To get information about the table 
csv_file.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    int64
 1   User Id        100 non-null    str  
 2   First Name     100 non-null    str  
 3   Last Name      100 non-null    str  
 4   Sex            100 non-null    str  
 5   Email          100 non-null    str  
 6   Phone          100 non-null    str  
 7   Date of birth  100 non-null    str  
 8   Job Title      100 non-null    str  
 9   Region         100 non-null    str  
dtypes: int64(1), str(9)
memory usage: 7.9 KB


In [ ]:

# statistical analysis 
csv_file.describe()

## Find the null values are there in the table
csv_file.isnull()

# Find the sum of null values 
csv_file.isnull().sum()

# In case if we have null value then we need to fill with value
csv_file.fillna(1)

# in case if we have null values in cell

In [ ]:
## Find the null values are there in the table
csv_file.isnull()

# Find the sum of null values 
csv_file.isnull().sum()

# In case if we have null value then we need to fill with value
csv_file.fillna(1)

In [100]:
len(csv_file)

100

In [20]:
# To rename the title name 
import random
csv_file.rename(columns= {"Email":"Email ID"})
csv_file["Salary"] = [random.randint(10000,99999)
for _ in range(len(csv_file))]
csv_file["Salary"] 
csv_file["Apprasial"] = csv_file["Salary"].apply(lambda X:X*2)
csv_file[["Salary", "Apprasial"]]



,Salary,Apprasial
0,26433,52866
1,59632,119264
2,79478,158956
3,30484,60968
4,81977,163954
...,...,...
95,62743,125486
96,24912,49824
97,87706,175412
98,44369,88738


In [37]:
# To find the Unique 
csv_file["Job Title"].unique()

<StringArray>
[                                            'Games developer',
                                              'Phytotherapist',
                                                   'Homeopath',
                                           'Market researcher',
                                          'Veterinary surgeon',
                                    'Waste management officer',
                                        'Intelligence analyst',
                                              'Hydrogeologist',
                                                      'Lawyer',
                                              'Engineer, site',
                               'Advertising account executive',
                                               'Warden/ranger',
 'Scientist, clinical (histocompatibility and immunogenetics)',
                                               'Social worker',
                                     'Agricultural consultant',
                          

In [38]:
csv_file = pd.read_csv(r"C:\Users\Vidhya\Python_Program\people-100.csv")
csv_file

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Region
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer,Asia
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist,Asia
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath,India
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher,US
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon,UK
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer,India
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister,India
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer,India
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist,India


In [ ]:
csv_file["mean_data"] = [csv_file["Salary"].mean() for _ in range(len(csv_file))]
csv_file["mean_data"]
csv_file
csv_file["Region"]
mean_Based_Region = csv_file.groupby('Region')["Apprasial"].mean()
mean_Based_Region


KeyError: 'Salary'